name: PR Validation

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13']

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        persist-credentials: false

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"

    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}

    - name: Install dependencies
      run: uv sync --all-extras

    - name: Run tests
      run: uv run pytest -v

    - name: Run linting
      run: |
        uv run black --check ecsify/ tests/
        uv run isort --check-only ecsify/ tests/
        uv run mypy ecsify/ --ignore-missing-imports

  conventional-commits:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        persist-credentials: false

    - name: Check conventional commits
      uses: webiny/action-conventional-commits@v1.3.0

  docker-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Build test image
      run: make docker-build-test

    - name: Run tests in Docker
      run: make docker-test
